// Get Products
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS_SUCCEEDED = 'GET_PRODUCTS_SUCCEEDED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

// Get Product Details
export const GET_PRODUCT_DETAILS_STARTED = 'GET_PRODUCT_DETAILS_STARTED';
export const GET_PRODUCT_DETAILS_SUCCEEDED = 'GET_PRODUCT_DETAILS_SUCCEEDED';
export const GET_PRODUCT_DETAILS_FAILED = 'GET_PRODUCT_DETAILS_FAILED';

// remove Product
export const REMOVE_PRODUCT_STARTED = 'REMOVE_PRODUCT_STARTED';
export const REMOVE_PRODUCT_SUCCEEDED = 'REMOVE_PRODUCT_SUCCEEDED';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

//Get Specific Product
export const GET_SPECIFIC_PRODUCTS_STARTED = 'GET_SPECIFIC_PRODUCTS_STARTED';
export const GET_SPECIFIC_PRODUCTS_SUCCEEDED = 'GET_SPECIFIC_PRODUCTS_SUCCEEDED';
export const GET_SPECIFIC_PRODUCTS_FAILED = 'GET_SPECIFIC_PRODUCTS_FAILED';

//Get All Categories
export const SELECT_CATEGORY_STARTED = 'SELECT_CATEGORY_STARTED';
export const SELECT_CATEGORY_SUCCEEDED = 'SELECT_CATEGORY_SUCCEEDED';
export const SELECT_CATEGORY_FAILED = 'SELECT_CATEGORY_FAILED';

//Get Single Product

export const GET_SINGLE_PRODUCTS_STARTED = 'GET_SINGLE_PRODUCTS_STARTED';
export const GET_SINGLE_PRODUCTS_SUCCEEDED = 'GET_SINGLE_PRODUCTS_SUCCEEDED';
export const GET_SINGLE_PRODUCTS_FAILED = 'GET_SINGLE_PRODUCTS_FAILED';

//Add Cart
export const ADD_CART_STARTED = 'ADD_CART_STARTED';
export const ADD_CART_SUCCEEDED = 'ADD_CART_SUCCEEDED';
export const ADD_CART_FAILED = 'ADD_CART_FAILED';

//Update Cart
export const UPDATE_CART_STARTED = 'UPDATE_CART_STARTED';
export const UPDATE_CART_SUCCEEDED = 'UPDATE_CART_SUCCEEDED';
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED';

//get Carts
export const GET_CARTS_STARTED = 'GET_CARTS_STARTED';
export const GET_CARTS_SUCCEEDED = 'GET_CARTS_SUCCEEDED';
export const GET_CARTS_FAILED = 'GET_CARTS_FAILED';
